name = "FermiDiracOperatorExpansion"
uuid = "33afacd8-8107-4a45-99dc-008ba02c4a67"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
GershgorinDiscs = "1acd937f-ba38-4cfb-ac8e-9b470edff748"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
Roots = "2.2.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
