name = "FermiDiracOperatorExpansion"
uuid = "33afacd8-8107-4a45-99dc-008ba02c4a67"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ConjugateGradient = "f400940f-8640-4bea-acd3-3d881d7c7dbd"
GershgorinDiscs = "1acd937f-ba38-4cfb-ac8e-9b470edff748"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
IterativeSolvers = "0.9.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
